version: '3.8'

services:
  postgres-fts-demo:
    image: postgres-fts-demo:1.0.0-SNAPSHOT
    container_name: postgres-fts-demo
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    networks:
      fts-network:

  postgres:
    image: postgres:14.8-alpine
    container_name: postgres
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      fts-network:

networks:
  fts-network:
