spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: com.github.kruzuzdyak.repository.hqlextension.PostgresSearchHibernateDialect
        format_sql: true

server:
  port: 8080